# Generated by Django 2.2.1 on 2019-06-03 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=100)),
                ('cellphone', models.IntegerField(max_length=10)),
                ('pqr_text', models.CharField(max_length=2000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=2000)),
                ('answer_date', models.DateTimeField(verbose_name='date published')),
                ('pqr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.PQR')),
            ],
        ),
    ]
