# Generated by Django 2.2.1 on 2019-06-03 22:09

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_answer_pqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqr',
            name='cellphone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
